#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Michael Koefinger, Johannes Kepler University
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
# Description: Sweep the lna_inv sizing knobs through VACASK small-signal runs, NF and Gm per point

"""What the sizing knobs buy the inverter LNA, measured rather than estimated.

    python3 scripts/lna_inv_sweep.py [--points robust] [--write]

`lna_inv_sizing.py` supplies `design(**kw)`, `inc_text(d)`, the point lists and
their table columns. Every point re-sizes the LNA, writes its include beside a
small-signal-only copy of the netlisted lna_inv_tb_sp bench, runs VACASK (op,
acsp, ac, noise: milliseconds) and reads the numbers back through
`lna_inv_post.small_signal`, so the sweep and the bench report agree. The
netlist is parameterised, so `make netlist-vacask` netlists it once and this
never touches it.

NF is reported with the bench's own load resistor taken out of the output noise.
"""

import argparse
import glob
import os
import re
import subprocess
import sys
import tempfile

import lna_inv_post as post
import lna_inv_sizing as sz
import vacask_rc

DECK = "lna_inv_tb_sp.spectre"
INC = "lna_inv_sizes.inc"


def small_signal_deck(text):
    """Drop the HB analyses and the alters, keep op, acsp, ac and noise."""
    keep = [line for line in text.splitlines()
            if not line.strip().startswith(("analysis hb", "alter instance", "sweep "))]
    return "\n".join(keep) + "\n"


def run_point(deck_text, inc_text, workdir):
    # every point runs in the same directory, so a failed one must not read the last one's raws
    for f in glob.glob(os.path.join(workdir, "*.raw")):
        os.remove(f)
    with open(os.path.join(workdir, DECK), "w") as fh:
        fh.write(deck_text)
    with open(os.path.join(workdir, INC), "w") as fh:
        fh.write(inc_text)
    # -sp: the bench's postprocess path is relative to simulations/, not to this directory
    r = subprocess.run(["vacask", "-sp", DECK], cwd=workdir, capture_output=True, text=True)
    if r.returncode or re.search(r"aborted|failed|error", r.stdout + r.stderr, re.I):
        return None
    m = post.small_signal(post.Raws(workdir))
    return m if "nf_db" in m else None


def sweep(points="sweep"):
    with open(os.path.join(post.SIM, DECK)) as fh:
        deck = small_signal_deck(fh.read())
    pdk_rc = os.path.join(os.environ["PDK_ROOT"], os.environ["PDK"], "libs.tech", "vacask", ".vacaskrc.toml")
    rows = []
    with tempfile.TemporaryDirectory() as d:
        vacask_rc.write_rc(pdk_rc, d)
        pts = sz.robust_points() if points == "robust" else sz.sweep_points()
        cols = sz.robust_columns if points == "robust" else sz.sweep_columns
        for kw in pts:
            try:
                des = sz.design(**kw)
            except ValueError as e:
                # a point the sizing cannot match is a result, not a crash
                rows.append((sz.sweep_columns_unmatched(kw, str(e)), None))
                continue
            rows.append((cols(des), run_point(deck, sz.inc_text(des), d)))
    return rows


def table(rows):
    labels = list(rows[0][0].keys())
    out = ["| " + " | ".join(labels) + " | **NF dB** | NF with load dB | Gm,eff mS | S11 at F0 dB | Idd mA |",
           "|" + "---|" * (len(labels) + 5)]
    for cols, m in rows:
        head = " | ".join(str(v) for v in cols.values())
        if m is None:
            out.append("| %s | aborted | | | | |" % head)
            continue
        out.append("| %s | **%.2f** | %.2f | %.1f | %.1f | %.2f |"
                   % (head, m["nf_db"], m["nf_with_load_db"], m["gm_eff_ms"], m["s11_db"], m["idd_ma"]))
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--points", choices=("sweep", "robust"), default="sweep",
                    help="robust: the nominal design with one thing moved at a time, from lna_inv_sizing.robust_points()")
    a = ap.parse_args()
    body = table(sweep(a.points))
    print(body)
    if a.write:
        if a.points == "robust":
            doc = os.path.join(post.MACRO, "doc", "lna_inv_robust.md")
            head = ("Description: lna_inv robustness, the nominal design with one thing moved at a time, measured in VACASK\n-->\n\n"
                    "# lna_inv robustness\n\nGenerated by `scripts/lna_inv_sweep.py --points robust`, rebuild with "
                    "`make robust`. Small-signal VACASK at TT, 27 C, the nominal sizes throughout: each row moves one "
                    "thing the way a part tolerance, the pad's spread, a width error or the load node's "
                    "parasitics would, see `robust_points()` in `scripts/lna_inv_sizing.py`. NF excludes the bench load.")
        else:
            doc = os.path.join(post.MACRO, "doc", "lna_inv_sweep.md")
            head = ("Description: lna_inv sizing sweep, NF and Gm measured in VACASK per point\n-->\n\n"
                    "# lna_inv sizing sweep\n\nGenerated by `scripts/lna_inv_sweep.py`, rebuild with "
                    "`make sweep`. Small-signal VACASK at TT, 27 C, every point re-sized by "
                    "`scripts/lna_inv_sizing.py`. NF excludes the bench load.")
        with open(doc, "w") as fh:
            fh.write("<!--\nSPDX-FileCopyrightText: 2026 Michael Koefinger, Johannes Kepler University\n"
                     "SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1\n" + head + "\n\n" + body + "\n")
        print("wrote %s" % doc)
    return 0


if __name__ == "__main__":
    sys.exit(main())
