#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Michael Koefinger, Johannes Kepler University
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
# Description: Write the netlist directory's VACASK config, with the PDK's own kept intact

"""Merge extra include directories into the PDK's .vacaskrc.toml.

    python3 vacask_rc.py --pdk-rc <file> --out <dir> [--add <dir> ...]

VACASK reads configuration files in four places (config/vacaskrc-sample.toml):
system, home, the STARTUP directory and the TOPLEVEL NETLIST directory. Only the
last one is independent of where vacask is started, so that is where this writes.

`[Paths].include_path_prefix` is searched before the builtin include path, so the
PDK's own model libraries keep resolving and the directories given with --add are
added in front. The PDK's file is parsed and re-emitted rather than appended to,
because a second [Paths] table or a repeated key is a TOML error.
"""

import argparse
import os
import sys

try:
    import tomllib                      # 3.11+
except ImportError:                     # pragma: no cover
    try:
        import tomli as tomllib
    except ImportError:
        tomllib = None


def dumps(obj):
    """Emit the subset of TOML these config files use: tables of scalars and string lists."""
    def val(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, (int, float)):
            return repr(v)
        if isinstance(v, (list, tuple)):
            return "[ " + ", ".join(val(x) for x in v) + " ]"
        return '"%s"' % str(v).replace("\\", "\\\\").replace('"', '\\"')

    top = [(k, v) for k, v in obj.items() if not isinstance(v, dict)]
    tables = [(k, v) for k, v in obj.items() if isinstance(v, dict)]
    out = ["# generated by scripts/vacask_rc.py, do not edit",
           "# the PDK's own configuration with the include path extended"]
    out += ["%s = %s" % (k, val(v)) for k, v in top]
    for name, tbl in tables:
        out.append("")
        out.append("[%s]" % name)
        out += ["%s = %s" % (k, val(v)) for k, v in tbl.items()]
    return "\n".join(out) + "\n"


def write_rc(pdk_rc, out, add=()):
    """Write out/.vacaskrc.toml, the PDK's config with the directories in add in front of its include path."""
    if not os.path.isfile(pdk_rc):
        sys.exit("%s not found: is $PDK the one that ships the VACASK collateral?" % pdk_rc)
    dst = os.path.join(out, ".vacaskrc.toml")
    extra = [os.path.abspath(d) for d in add if os.path.isdir(d)]

    def copy_verbatim():
        with open(pdk_rc, "rb") as fh:
            body = fh.read()
        with open(dst, "wb") as fh:
            fh.write(body)
        return dst

    if tomllib is None or not extra:
        # No parser, or nothing to add: the PDK's file verbatim is still correct.
        if extra:
            print("  tomllib missing, copied the PDK rc unchanged, "
                  "includes outside the PDK will not resolve")
        return copy_verbatim()

    with open(pdk_rc, "rb") as fh:
        cfg = tomllib.load(fh)
    paths = dict(cfg.get("Paths", {}))
    have = list(paths.get("include_path_prefix", []))
    paths["include_path_prefix"] = extra + [p for p in have if p not in extra]
    cfg["Paths"] = paths
    text = dumps(cfg)
    # Re-emitting is only safe if it round-trips: the PDK's file may use TOML
    # this writer does not cover (nested tables, inline tables, dates). Rather
    # than leave a config VACASK would silently ignore, fall back to its file.
    try:
        back = tomllib.loads(text)
        assert back == cfg
    except Exception as exc:
        print("  WARNING: cannot re-emit %s (%s)" % (pdk_rc, exc))
        print("  copied it unchanged, includes outside the PDK will not resolve")
        return copy_verbatim()
    with open(dst, "w") as fh:
        fh.write(text)
    print("  %s: include path + %s" % (dst, ", ".join(extra)))
    return dst


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pdk-rc", required=True, help="the PDK's .vacaskrc.toml")
    ap.add_argument("--out", required=True, help="directory holding the toplevel netlist")
    ap.add_argument("--add", action="append", default=[],
                    help="directory to put in front of the include path (repeatable)")
    ap.add_argument("--run", metavar="NETLIST", default=None,
                    help="after writing the config, run vacask on NETLIST from --out")
    a = ap.parse_args()
    write_rc(a.pdk_rc, a.out, a.add)
    if not a.run:
        return 0
    net = os.path.abspath(a.run)
    os.chdir(a.out)                 # vacask writes its raws into the current directory
    os.execvp("vacask", ["vacask", net])


if __name__ == "__main__":
    sys.exit(main())
